server:
  port: 0

spring:
  oauth2:
    resource:
      userInfoUri: http://192.168.0.08:9999/uaa/user

management:
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

  client:
    serviceUrl:
      defaultZone: http://192.168.0.08:8761/eureka/
    registryFetchIntervalSeconds: 5

logging:
  level:
    se.callista: INFO
